name: "[WORKFLOW CALL] Add label to issue v1"

on:
  workflow_call:
   
    inputs:
      label:
        description: "Label to add to the issue"
        required: true
        type: string

    secrets:
      REPOS_GITHUB_TOKEN:
        required: true

jobs:
  common_issue_add_label:
    runs-on: ubuntu-latest
    steps:
    - name: "Add label to the issue"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.REPOS_GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['${{ inputs.label }}']
          })