name: "[WORKFLOW CALL] Issue comment v1"

on:
  workflow_call:
   
    inputs:
      comment:
        description: "Comment to post"
        required: true
        type: string        

    secrets:
      REPOS_GITHUB_TOKEN:
        required: true

jobs:
  common_issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: "Issue comment"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.REPOS_GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ inputs.comment }}
          })