name: "[WORKFLOW CALL] Dismiss project v1"

on:
  workflow_call:
    inputs:
      project_id:
        description: "Application name"
        required: true
        type: string    
      deploy_id:
        description: "ID for namespace and helm release name"
        required: true
        type: string
      remove_ns:
        description: "Remove or not NS by werf"
        required: false
        default: false
        type: boolean

    secrets:
      HARBOR_USERNAME: 
        required: true
      HARBOR_PASSWORD: 
        required: true
      HARBOR_HOST: 
        required: true
      KUBECONFIG_DATA: 
        required: true
 
env:
  WERF_REPO: ${{ format ('{0}/images/{1}', secrets.HARBOR_HOST, inputs.project_id) }}
  WERF_REPO_CONTAINER_REGISTRY: harbor
  WERF_DIR: ${{ format ('{0}/werf' , inputs.project_id) }}
  
jobs:
  dismiss:
    name: "Dismiss project"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout code"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Login to Harbor"
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.HARBOR_HOST }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    
    - name: "Base64 kubeconfig"
      run: |
        echo 'kubeconfig_base64_data<<EOF' >> $GITHUB_ENV
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    
    - name: "Dismiss project"
      uses: werf/actions/dismiss@v1.2
      env:
        WERF_WITH_NAMESPACE: ${{ inputs.remove_ns }}
      with: 
        kube-config-base64-data: ${{ env.kubeconfig_base64_data }}
        env: ${{ inputs.deploy_id }}

    - name: "Remove NS"
      if: ${{ failure() }}
      continue-on-error: true
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ env.kubeconfig_base64_data }}
      with:
        command: kubectl delete namespace ${{ format ('{0}-{1}', inputs.project_id, inputs.deploy_id) }}